baseurl = "https://example.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "World AI 世界 AI"
theme = "dream"



# [services]
[services.disqus]
shortname = "your-disqus-shortname"
# [services.googleAnalytics]
# ID = ""

[params]
lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "/me/background.jpg"
# backgroundImageDark = ""

author = "John AI"
# description = ""
# avatar = "/img/avatar.png"
headerTitle = "World AI 世界 AI"
# motto = ""

# footerBottomText = ""

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
# VALINE_LANGUAGE = ""

# email = ""

siteStartYear = 2016

# favicon = "/favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
# showSummaryCoverInPost = true
# hasTwitterEmbed = true

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy年MM月dd日"
